Update Quick Start sample #3038
auth0-samples/auth0-react-native-sample pull request #55
Opened 2022-01-10 12:17 UTC by poovamraj

**Description**

- We have migrated React Native version from 0.64 to 0.66.
- This made us increase the minimum iOS support to 11
- Used functional component instead of class based component
- Updated initial README

2022-01-10 13:47 UTC, Widcket commented on 00-Login/app/App.js
> +    let loggedIn = accessToken === null ? false : true;
The explicit `false` and `true` ar not necessary

2022-01-10 13:50 UTC, Widcket requested changes
There are some changes missing, compared to the diff from the upgrade helper: https://react-native-community.github.io/upgrade-helper/?from=0.64.0&to=0.66.4

2022-01-10 16:09 UTC, poovamraj commented
Thanks a lot @Widcket, I tried updating using the CLI provided by RN and looks like it didn't apply these infos. Anyways I have updated them now 👍

2022-01-11 15:37 UTC, Widcket approved these changes

2022-01-11 15:54 UTC, merged